version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:55432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  nourybot:
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - "./public/uploads/:/public/uploads"
    ports:
      - "127.0.0.1:42069:8080"
    depends_on:
      - database
volumes:
  data:
