version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:55432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  nourybot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
volumes:
  data:
